### ISSUE TITLE
PUT to report errors

### ISSUE THREAD

**Issue by martinsookael** [jayJs/jay-npm#4]
https://github.com/jayJs/jay-npm/blob/master/lib/jay.js#L129
          protectedCallback(res, callback, {error: err})
would work better perhaps:
          protectedCallback(res, callback, {error: body.error})

**Comment by martinsookael** [comment]
That of course would cause this:

TypeError: Cannot read property 'error' of undefined
    at Object.callback (/node_modules/jay-npm/lib/jay.js:131:56)
    at Request._callback (node_modules/jay-npm/node_modules/kaiseki/lib/kaiseki.js:391:12)
    at self.callback (node_modules/jay-npm/node_modules/kaiseki/node_modules/request/request.js:129:22)
